version: "3.6"
services:
    hasura:
        image: hasura/graphql-engine:latest
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: ${CONTAINER_NAME}
        ports:
            - ${HASURA_PORT}:8080
        environment:
            HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
            HASURA_GRAPHQL_METADATA_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
            HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, action-handler-log
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
            HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
            HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
            ACTION_BASE_URL: ${ACTION_BASE_URL}
            HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
